---
- name: Set permissions on socket - owner
  lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;?listen.owner' line='listen.owner = www-data'"

- name: Set permissions on socket - group
  lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;?listen.group' line='listen.group = www-data'"

- name: Set permissions on socket - mode
  lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;?listen.mode' line='listen.mode = 0660'"

- name: Ensure timezone is set in fpm php.ini
  lineinfile: dest=/etc/php5/fpm/php.ini
              backrefs=yes
              regexp='date.timezone ='
              line='date.timezone = {{ config.timezone }}'

- name: Disabling opcache
  lineinfile: dest=/etc/php5/fpm/php.ini
              backrefs=yes
              regexp=';opcache.enable=1'
              line='opcache.enable=0'
  when: not php.apc

- name: Enabling opcache
  lineinfile: dest=/etc/php5/fpm/php.ini
              backrefs=yes
              regexp=';opcache.enable=0'
              line='opcache.enable=1'
  when: php.apc

- name: Set upload_max_filesize to 5M
  lineinfile: dest=/etc/php5/fpm/php.ini
              backrefs=yes
              regexp='upload_max_filesize\s*=\s*2M'
              line='upload_max_filesize = 5M'
              state=present

- name: Set expose_php to Off
  lineinfile: dest=/etc/php5/fpm/php.ini
              backrefs=yes
              regexp='expose_php = On'
              line='expose_php = Off'
              state=present